name: Jean-Hugues Pinson
url: http://jhpinson.github.io/
description: Unix is user friendly. It's just very particular about who its friends are.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']