name: Jean-Hugues Pinson
url: http://jhpinson.github.io/
description: Web Developer

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']